labs/stox corrected/config/routes.rb
Stox::Application.routes.draw do

  match '/quote' => 'stocks#quote', :via => :get
  match '/quote' => 'stocks#yahoo', :via => :post
  match '/tally' => 'stocks#tally'

  root :to => 'stocks#quote'

end

labs/stox corrected/app/models/stock.rb
# == Schema Information
#
# Table name: stocks
#
#  id         :integer          not null, primary key
#  symbol     :string(255)
#  quote      :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Stock < ActiveRecord::Base
end

labs/stox corrected/app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def quote
  end
  def yahoo
    @symbol = params[:symbol].upcase
    count = params[:count].to_i
    @quotes = count.times.map{sleep 5; YahooFinance::get_quotes(YahooFinance::StandardQuote, @symbol)[@symbol].lastTrade}
    @avg = @quotes.inject(&:+) / count
    @quotes.each{|q| Stock.create(:symbol => @symbol, :quote => q)}
  end
  def tally
    stocks = Stock.select(:symbol).uniq
    symbols = stocks.map{|stock| stock.symbol}
    @output = {}
    symbols.each do |symbol|
      @output[symbol] = Stock.where(:symbol => symbol)
    end
  end
end

labs/stox corrected/app/views/stocks/quote.html.erb
<%= form_tag do %>
  <%= text_field_tag 'symbol' %>
  <br />
  <%= number_field_tag 'count' %>
  <br />
  <%= submit_tag 'Get Quote' %>
<% end %>

labs/stox corrected/app/views/stocks/tally.html.erb
<% @output.each do |symbol, stocks| %>
  <h1><%= symbol %></h1>
  <ul>
    <% stocks.each do |stock| %>
      <li><%= number_to_currency stock.quote %></li>
    <% end %>
  </ul>
<% end %>

labs/stox corrected/app/views/stocks/yahoo.html.erb
<h1><%= @symbol %></h1>
<h2><%= number_to_currency @avg %></h2>
<ul>
  <% @quotes.each do |quote| %>
    <li><%= number_to_currency quote %></li>
  <% end %>
</ul>

<%= link_to "Home", root_path %> :: <%= link_to "Tally", tally_path %>