labs/animal_kingdom/config/routes.rb
AnimalKingdom::Application.routes.draw do

resources :animals

  root :to => 'home#index'

end

labs/animal_kingdom/app/models/animal.rb
# == Schema Information
#
# Table name: animals
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  species    :string(255)
#  photo      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Animal < ActiveRecord::Base
	validates :name, :species, :photo, :presence => true
end

labs/animal_kingdom/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
	def index
		@animals = Animal.all
	end

	def show
		animal_id = params[:id]
		@animal = Animal.find(animal_id)
	end

	def new
		@animal = Animal.new
	end

	def edit
		@animal = Animal.find(params[:id])
	end

	def create
		@animal = Animal.new(params[:animal])
		
		if @animal.save 
			redirect_to animals_path
		else
			render :new #means that the page should render 
		end
	end

	def update
		@animal = Animal.find(params[:id])

		if @animal.update_attributes(params[:animal])
			redirect_to @animal
		else
			render :edit
		end
	end

	def destroy
		animal = Animal.find(params[:id])
		animal.delete
		redirect_to animals_path
	end

end

labs/animal_kingdom/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

labs/animal_kingdom/app/views/animals/_form.html.erb
<ul class="errors">
<% @animal.errors.full_messages.each do |error| %>
<li><%= error %></li>
<% end %>
</ul><!-- .errors -->

<%= form_for @animal do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div><!-- field -->

	<div class="field">
		<%= f.label :species %>
		<%= f.text_field :species %>
	</div><!-- field -->

	<div class="field">
		<%= f.label :photo %>
		<%= f.text_field :photo %>
	</div><!-- field -->

	<%= f.submit %>	
<% end %>

labs/animal_kingdom/app/views/animals/edit.html.erb
<h1>Edit Animal</h1>

<%= render 'form' %>

labs/animal_kingdom/app/views/animals/index.html.erb
<ul>
	<% @animals.each do |animal| %>
	<li><%= link_to animal.name, animal_path(animal) %></li>
	<% end %>
</ul>

labs/animal_kingdom/app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form' %>

labs/animal_kingdom/app/views/animals/show.html.erb
<h1><%= link_to "delete", animal_path(@animal), :method => :delete, :confirm => "Are you sure?" %></h1>
<h1> <%= link_to @animal.name,edit_animal_path(@animal) %></h1>
<p> <%= @animal.species %></p>
<%= image_tag @animal.photo %>