labs/cookiedemo/config/routes.rb
Cookiedemo::Application.routes.draw do
  resources :ninjas

  match'/login' => 'session#new', :via => :get
  match'/login' => 'session#create', :via => :post
  match'/logout' => 'session#destroy', :via => :get

end

labs/cookiedemo/app/models/ninja.rb
class Ninja < ActiveRecord::Base
	has_secure_password
end

labs/cookiedemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user
  private

  def authenticate_user
  	if session[:user_id]
  		@authenticated_user = Ninja.find(session[:user_id])
  	else
  		@authenticated_user = nil
	end
   end
end

labs/cookiedemo/app/controllers/ninjas_controller.rb
class NinjasController < ApplicationController
  # GET /ninjas
  # GET /ninjas.json

  def index
    @ninjas = Ninja.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ninjas }
    end
  end

  # GET /ninjas/1
  # GET /ninjas/1.json
  def show
    @ninja = Ninja.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ninja }
    end
  end

  # GET /ninjas/new
  # GET /ninjas/new.json
  def new
    @ninja = Ninja.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ninja }
    end
  end

  # GET /ninjas/1/edit
  def edit
    @ninja = Ninja.find(params[:id])
  end

  # POST /ninjas
  # POST /ninjas.json
  def create
    #raise params.inspect
    @ninja = Ninja.new(params[:ninja])

    #name = params[:ninja][:name]
    #session[:name] = name

    respond_to do |format|
      if @ninja.save
        format.html { redirect_to @ninja, notice: 'Ninja was successfully created.' }
        format.json { render json: @ninja, status: :created, location: @ninja }
      else
        format.html { render action: "new" }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ninjas/1
  # PUT /ninjas/1.json
  def update
    @ninja = Ninja.find(params[:id])

    respond_to do |format|
      if @ninja.update_attributes(params[:ninja])
        format.html { redirect_to @ninja, notice: 'Ninja was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ninja.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ninjas/1
  # DELETE /ninjas/1.json
  def destroy
    @ninja = Ninja.find(params[:id])
    @ninja.destroy

    respond_to do |format|
      format.html { redirect_to ninjas_url }
      format.json { head :no_content }
    end
  end
end

labs/cookiedemo/app/controllers/session_controller.rb
class SessionController < ApplicationController

	def new
	end

	def create
		ninja = Ninja.find_by_name(params[:name]) 			#find_by_name - rails knows that you have a name field
		if ninja && ninja.authenticate(params[:password]) 		#if password is valid to the ninja you typed in, then 
			session[:user_id] = ninja.id			#saves the id to server memory - server will now remember who you are
			redirect_to ninjas_path 		#sends you to the index page
		else
			render :new #if passworld is not correct, go back to the login screen.
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to ninjas_path
	end
end

labs/cookiedemo/app/helpers/application_helper.rb
module ApplicationHelper
	def show_dynamic_links
		if @authenticated_user
			link_to @authenticated_user.name, logout_path
		else
			link_to "Login", login_path
		end
	end
end

labs/cookiedemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookiedemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
	<%= show_dynamic_links %>
	<%= link_to "Ninjas", ninjas_path %>
</nav>

<%= yield %>

</body>
</html>

labs/cookiedemo/app/views/ninjas/_form.html.erb
<%= form_for(@ninja) do |f| %>
  <% if @ninja.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ninja.errors.count, "error") %> prohibited this ninja from being saved:</h2>

      <ul>
      <% @ninja.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weapons %><br />
    <%= f.text_field :weapons %>
  </div>

    <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

      <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

labs/cookiedemo/app/views/ninjas/index.html.erb
<h1>The current ninja is : <%= @authenticated_user.try(:name) %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Weapons</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ninjas.each do |ninja| %>
  <tr>
    <td><%= ninja.name %></td>
    <td><%= ninja.weapons %></td>
    <td><%= link_to 'Show', ninja %></td>
    <td><%= link_to 'Edit', edit_ninja_path(ninja) %></td>
    <td><%= link_to 'Destroy', ninja, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ninja', new_ninja_path %>

labs/cookiedemo/app/views/ninjas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ninja.name %>
</p>

<p>
  <b>Weapons:</b>
  <%= @ninja.weapons %>
</p>


<%= link_to 'Edit', edit_ninja_path(@ninja) %> |
<%= link_to 'Back', ninjas_path %>